name: "Infrastructure Validate"
on:
    pull_request:
        paths: ["infra/**", ".github/workflows/infra-validate.yml"]

jobs:
    bicep-build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
            - run: az bicep build --file infra/main.bicep
            - run: az bicep lint --file infra/main.bicep
